backend:
  name: github
  repo: remkarl/wolhwagalbi # ðŸ”´ CHANGE if repo name differs
  branch: main
  client_id: IDOv23li1TvItrsW0HYkky # ðŸ”´ CHANGE if you have your own GitHub OAuth app
  client_secret: 1ce813f276fe0b8f390920989e800d80953fc0deT # ðŸ”´ CHANGE

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: https://wolhwagalbi.ph
logo_url: https://wolhwagalbi.ph/assets/logo.png

collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "pages" }
      - { label: "Body", name: "body", widget: "markdown" }
  
  - name: "posts"
    label: "Announcements"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }